// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var AlgebraException;
    return AlgebraException = (function() {
      function AlgebraException(message) {
        this.message = message;
      }

      AlgebraException.prototype.toString = function() {
        return "AlgebraException: " + this.message;
      };

      return AlgebraException;

    })();
  });

}).call(this);
