// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(["JSAlgebra/variable", "JSAlgebra/constant", "JSAlgebra/algebraException"], function(Variable, Constant, AlgebraException) {
    var Equation;
    return Equation = (function() {
      function Equation(leftTerms, rightTerms) {
        var term, _i, _j, _len, _len1;
        this.leftTerms = [];
        this.rightTerms = [];
        for (_i = 0, _len = leftTerms.length; _i < _len; _i++) {
          term = leftTerms[_i];
          this.leftTerms.push(Equation.handleInputTerm(term));
        }
        for (_j = 0, _len1 = rightTerms.length; _j < _len1; _j++) {
          term = rightTerms[_j];
          this.rightTerms.push(Equation.handleInputTerm(term));
        }
      }

      Equation.handleInputTerm = function(term) {
        var c, constant, constantWithPower, d, fractional, n, p, power, v, variable, _ref, _ref1, _ref2;
        if (typeof term === 'string' || (term instanceof String)) {
          constant = /^-?\d+(\.\d+)?$/;
          constantWithPower = /^-?\d+(\.\d+)?\*\*-?\d+(\.\d+)?$/;
          variable = /^[A-Za-z_]+([0-9]+)?(-\d+)?$/;
          fractional = /^-?\d+(\.\d+)?\/\d+(\.\d+)?$/;
          power = /^[A-Za-z_]+([0-9]+)?(-\d+)?\*\*-?\d+(\.\d+)?$/;
          if (term.match(constant) != null) {
            c = new Constant(parseFloat(term));
            c.simplify();
            return c;
          } else if (term.match(variable) != null) {
            return new Variable(term);
          } else if (term.match(fractional) != null) {
            _ref = term.split("/"), n = _ref[0], d = _ref[1];
            c = new Constant(parseFloat(n), parseFloat(d));
            c.simplify();
            return c;
          } else if (term.match(power) != null) {
            _ref1 = term.split("**"), v = _ref1[0], p = _ref1[1];
            return new Variable(v, parseFloat(p));
          } else if (term.match(constantWithPower) != null) {
            _ref2 = term.split("**"), v = _ref2[0], p = _ref2[1];
            v = new Constant(parseFloat(v));
            v.pow(parseFloat(p));
            return v;
          } else {
            throw new Error("Invalid term in equation: " + term);
          }
        } else if (typeof term === 'number' || (term instanceof Number)) {
          c = new Constant(term);
          c.simplify();
          return c;
        } else if (term.isTerm != null) {
          return term.copy();
        } else {
          throw new TypeError("Expected Variable, Constant, number, or string, got: " + term);
        }
      };

      Equation.prototype.solve = function(variable) {
        var e, leftTerm, leftTerms, power, rightTerm, rightTerms, root, term, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1;
        leftTerms = [];
        rightTerms = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if ((term.isVariable != null) && term.label === variable) {
            leftTerm = term.copy();
            leftTerms.push(leftTerm);
          } else {
            rightTerm = term.copy();
            rightTerm.pow(-1);
            rightTerms.push(rightTerm);
          }
        }
        _ref1 = this.rightTerms;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if ((term.isVariable != null) && term.label === variable) {
            leftTerm = term.copy();
            leftTerm.pow(-1);
            leftTerms.push(leftTerm);
          } else {
            rightTerm = term.copy();
            rightTerms.push(rightTerm);
          }
        }
        if (leftTerms.length === 0) {
          throw new AlgebraException("Variable to solve for was not in equation.");
        }
        for (root in leftTerms[0].roots) {
          if (leftTerms[0].roots[root] > 0) {
            for (_k = 0, _len2 = rightTerms.length; _k < _len2; _k++) {
              term = rightTerms[_k];
              term.pow(Math.pow(root, leftTerms[0].roots[root]));
            }
            leftTerms[0].roots[root] = 0;
          }
        }
        power = leftTerms[0].power;
        for (_l = 0, _len3 = leftTerms.length; _l < _len3; _l++) {
          term = leftTerms[_l];
          term.pow(1 / power);
        }
        for (_m = 0, _len4 = rightTerms.length; _m < _len4; _m++) {
          term = rightTerms[_m];
          term.pow(1 / power);
        }
        e = new Equation(leftTerms, rightTerms);
        return e.collectConstants();
      };

      Equation.prototype.collectConstants = function() {
        var a, constant, leftTerms, rightTerms, term, _i, _j, _len, _len1, _ref, _ref1;
        constant = new Constant(1);
        leftTerms = [];
        rightTerms = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if (term.isConstant != null) {
            a = term.copy();
            a.pow(-1);
            constant = constant.multiply(a);
          } else {
            leftTerms.push(term);
          }
        }
        _ref1 = this.rightTerms;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if (term.isConstant != null) {
            constant = constant.multiply(term);
          } else {
            rightTerms.push(term);
          }
        }
        constant.simplify();
        if (constant.evaluate() !== 1) {
          rightTerms.unshift(constant);
        }
        if (leftTerms.length === 0) {
          leftTerms.push(new Constant(1));
        }
        if (leftTerms.length === 0) {
          rightTerms.push(new Constant(1));
        }
        return new Equation(leftTerms, rightTerms);
      };

      Equation.prototype.replaceVariables = function(replacements) {
        var term, _i, _j, _len, _len1, _ref, _ref1, _results;
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if ((term.isVariable != null) && term.label in replacements) {
            term.label = replacements[term.label];
          }
        }
        _ref1 = this.rightTerms;
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if ((term.isVariable != null) && term.label in replacements) {
            _results.push(term.label = replacements[term.label]);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      Equation.prototype.getAllVariables = function() {
        var term, variableLabels, _i, _j, _len, _len1, _ref, _ref1;
        variableLabels = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if (term.isVariable != null) {
            variableLabels.push(term.label);
          }
        }
        _ref1 = this.rightTerms;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if (term.isVariable != null) {
            variableLabels.push(term.label);
          }
        }
        return variableLabels;
      };

      Equation.prototype.sub = function(values) {
        var equation, leftConstant, leftTerms, rightConstant, rightTerms, root, term, v, _i, _j, _len, _len1, _ref, _ref1;
        leftTerms = [];
        leftConstant = null;
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if (term.isVariable != null) {
            if (term.label in values) {
              if (values[term.label].isConstant != null) {
                v = values[term.label].copy();
              } else {
                v = new Constant(values[term.label]);
              }
              v.pow(term.power);
              for (root in term.roots) {
                if (root in v.roots) {
                  v.roots[root] += term.roots[root];
                } else {
                  v.roots[root] = term.roots[root];
                }
              }
              if (leftConstant != null) {
                leftConstant = leftConstant.multiply(v);
              } else {
                leftConstant = v;
              }
            } else {
              leftTerms.push(term);
            }
          } else if (term.isConstant != null) {
            if (leftConstant != null) {
              leftConstant = leftConstant.multiply(term);
            } else {
              leftConstant = term.copy();
            }
          }
        }
        rightTerms = [];
        rightConstant = null;
        _ref1 = this.rightTerms;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if (term.isVariable != null) {
            if (term.label in values) {
              if (values[term.label].isConstant != null) {
                v = values[term.label].copy();
              } else {
                v = new Constant(values[term.label]);
              }
              v.pow(term.power);
              for (root in term.roots) {
                if (root in v.roots) {
                  v.roots[root] += term.roots[root];
                } else {
                  v.roots[root] = term.roots[root];
                }
              }
              if (rightConstant != null) {
                rightConstant = rightConstant.multiply(v);
              } else {
                rightConstant = v;
              }
            } else {
              rightTerms.push(term);
            }
          } else if (term.isConstant != null) {
            if (rightConstant != null) {
              rightConstant = rightConstant.multiply(term);
            } else {
              rightConstant = term.copy();
            }
          }
        }
        if (leftTerms.length === 0 && rightTerms.length === 0 && (leftConstant != null) && (rightConstant != null)) {
          throw new AlgebraException("Inconsistent numbers substituted into equation.");
        }
        if (leftConstant != null) {
          leftTerms.unshift(leftConstant);
        }
        if (rightConstant != null) {
          rightTerms.unshift(rightConstant);
        }
        equation = new Equation(leftTerms, rightTerms);
        return equation.collectConstants();
      };

      Equation.prototype.substituteEquation = function(sourceEquation, variable, equivalencies) {
        var equation, item, leftTerms, rightTerms, root, solvedSource, term, variableEquivalencies, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
        if (equivalencies == null) {
          equivalencies = null;
        }
        if (equivalencies == null) {
          equivalencies = {
            get: []
          };
        }
        solvedSource = sourceEquation.solve(variable);
        variableEquivalencies = equivalencies.get(variable);
        leftTerms = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if ((term.isVariable != null) && (term.label === variable || (_ref1 = term.label, __indexOf.call(variableEquivalencies, _ref1) >= 0))) {
            _ref2 = solvedSource.rightTerms;
            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
              item = _ref2[_j];
              item = item.copy();
              item.pow(term.power);
              for (root in term.roots) {
                if (root in item.roots) {
                  item.roots[root] += root;
                } else {
                  item.roots[root] = root;
                }
              }
              leftTerms.push(item);
            }
          } else {
            leftTerms.push(term);
          }
        }
        rightTerms = [];
        _ref3 = this.rightTerms;
        for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
          term = _ref3[_k];
          if ((term.isVariable != null) && (term.label === variable || (_ref4 = term.label, __indexOf.call(variableEquivalencies, _ref4) >= 0))) {
            _ref5 = solvedSource.rightTerms;
            for (_l = 0, _len3 = _ref5.length; _l < _len3; _l++) {
              item = _ref5[_l];
              item = item.copy();
              item.pow(term.power);
              for (root in term.roots) {
                if (root in item.roots) {
                  item.roots[root] += root;
                } else {
                  item.roots[root] = root;
                }
              }
              rightTerms.push(item);
            }
          } else {
            rightTerms.push(term);
          }
        }
        equation = new Equation(leftTerms, rightTerms);
        return equation.collectConstants();
      };

      Equation.prototype.evaluate = function(variable, values) {
        var f;
        if (values == null) {
          values = null;
        }
        if (values != null) {
          f = this.solve(variable).sub(values);
        } else {
          f = this.solve(variable);
        }
        if (f.rightTerms.length === 1 && (f.rightTerms[0].isConstant != null)) {
          return f.rightTerms[0].evaluate();
        } else {
          return f;
        }
      };

      Equation.prototype.toString = function() {
        var leftHandSide, output, rightHandSide, term, _i, _j, _len, _len1, _ref, _ref1;
        output = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if ((term.isVariable != null) && term.power === 0) {

          } else {
            output.push(term.toString());
          }
        }
        leftHandSide = output.join(" * ");
        output = [];
        _ref1 = this.rightTerms;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if ((term.isVariable != null) && term.power === 0) {

          } else {
            output.push(term.toString());
          }
        }
        rightHandSide = output.join(" * ");
        return leftHandSide + " = " + rightHandSide;
      };

      Equation.prototype.toHTML = function(equationID, expression) {
        var divClass, divID, html, i, label, labelArray, labelID, leftTerms, power, rightTerms, root, rootEnd, rootStart, term, _i, _j, _k, _l, _len, _len1, _ref, _ref1, _ref2, _ref3;
        if (expression == null) {
          expression = false;
        }
        if (!expression) {
          divClass = "equation";
          if (equationID != null) {
            divID = "equation-" + equationID;
          } else {
            divID = "equation";
          }
        } else {
          divClass = "expression";
          if (equationID != null) {
            divID = "expression-" + equationID;
          } else {
            divID = "expression";
          }
        }
        html = '<div id="' + divID + '" class="' + divClass + '">';
        leftTerms = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if (term.isVariable != null) {
            if (term.power === 0) {

            } else {
              if (term.power === 1) {
                power = "";
              } else {
                power = "**" + term.power;
              }
              rootStart = "";
              rootEnd = "";
              for (root in term.roots) {
                if (term.roots[root] > 0) {
                  for (i = _j = 1, _ref1 = term.roots[root]; 1 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 1 <= _ref1 ? ++_j : --_j) {
                    rootStart += "(";
                    rootEnd += ")**(1/" + root + ")";
                  }
                }
              }
              labelArray = term.label.split("-");
              label = labelArray[0];
              labelID = labelArray[1] != null ? 'id="variable-' + term.label + '"' : "";
              leftTerms.push(rootStart + '<span class="variable"' + labelID + '>' + labelArray[0] + '</span>' + power + rootEnd);
            }
          } else {
            leftTerms.push(term);
          }
        }
        rightTerms = [];
        _ref2 = this.rightTerms;
        for (_k = 0, _len1 = _ref2.length; _k < _len1; _k++) {
          term = _ref2[_k];
          if (term.isVariable != null) {
            if (term.power === 0) {

            } else {
              if (term.power === 1) {
                power = "";
              } else {
                power = "**" + term.power;
              }
              labelArray = term.label.split("-");
              label = labelArray[0];
              labelID = labelArray[1] != null ? 'id="variable-' + term.label + '"' : "";
              rootStart = "";
              rootEnd = "";
              for (root in term.roots) {
                if (term.roots[root] > 0) {
                  for (i = _l = 1, _ref3 = term.roots[root]; 1 <= _ref3 ? _l <= _ref3 : _l >= _ref3; i = 1 <= _ref3 ? ++_l : --_l) {
                    rootStart += "(";
                    rootEnd += ")**(1/" + root + ")";
                  }
                }
              }
              rightTerms.push(rootStart + '<span class="variable"' + labelID + '>' + labelArray[0] + '</span>' + power + rootEnd);
            }
          } else {
            rightTerms.push(term);
          }
        }
        html += leftTerms.join(" * ") + " = " + rightTerms.join(" * ") + "</div>";
        return html;
      };

      Equation.prototype.toMathML = function(equationID, expression) {
        var html, leftSide, leftTermsBottom, leftTermsLeft, leftTermsTop, mathClass, mathID, rightSide, rightTermsBottom, rightTermsLeft, rightTermsTop, t, term, _i, _j, _len, _len1, _ref, _ref1;
        if (expression == null) {
          expression = false;
        }
        if (!expression) {
          mathClass = "equation";
          if (equationID != null) {
            mathID = "equation-" + equationID;
          } else {
            mathID = "equation";
          }
        } else {
          mathClass = "expression";
          if (equationID != null) {
            mathID = "expression-" + equationID;
          } else {
            mathID = "expression";
          }
        }
        html = '<div id="' + mathID + '" class="' + mathClass + '"><math xmlns="http://www.w3.org/1998/Math/MathML">';
        leftTermsLeft = [];
        leftTermsTop = [];
        leftTermsBottom = [];
        _ref = this.leftTerms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          term = _ref[_i];
          if (term.isVariable != null) {
            if (term.power === 0) {

            } else {
              if (term.power > 0) {
                leftTermsTop.push(term.toMathML(mathID));
              } else {
                t = term.copy();
                t.pow(-1);
                leftTermsBottom.push(t.toMathML(mathID));
              }
            }
          } else {
            leftTermsLeft.push(term.toMathML());
          }
        }
        rightTermsLeft = [];
        rightTermsTop = [];
        rightTermsBottom = [];
        _ref1 = this.rightTerms;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          term = _ref1[_j];
          if (term.isVariable != null) {
            if (term.power === 0) {

            } else {
              if (term.power > 0) {
                rightTermsTop.push(term.toMathML(mathID));
              } else {
                t = term.copy();
                t.pow(-1);
                rightTermsBottom.push(t.toMathML(mathID));
              }
            }
          } else {
            rightTermsLeft.push(term.toMathML());
          }
        }
        leftSide = [];
        if (leftTermsLeft.length > 0) {
          leftSide.push(leftTermsLeft.join("<mo>&middot;</mo>"));
        }
        if (leftTermsTop.length > 0 && leftTermsBottom.length > 0) {
          leftSide.push("<mfrac><mrow>" + leftTermsTop.join("<mo>&middot;</mo>") + "</mrow><mrow>" + leftTermsBottom.join("<mo>&middot;</mo>") + "</mrow></mfrac>");
        } else if (leftTermsTop.length > 0) {
          leftSide.push(leftTermsTop.join("<mo>&middot;</mo>"));
        } else if (leftTermsBottom.length > 0) {
          leftSide.push("<mfrac><mrow><mn>1</mn></mrow><mrow>" + leftTermsBottom.join("<mo>&middot;</mo>") + "</mrow></mfrac>");
        }
        html += leftSide.join("<mo>&middot;</mo>") + "<mo>=</mo>";
        rightSide = [];
        if (rightTermsLeft.length > 0) {
          rightSide.push(rightTermsLeft.join("<mo>&middot;</mo>"));
        }
        if (rightTermsTop.length > 0 && rightTermsBottom.length > 0) {
          rightSide.push("<mfrac><mrow>" + rightTermsTop.join("<mo>&middot;</mo>") + "</mrow><mrow>" + rightTermsBottom.join("<mo>&middot;</mo>") + "</mrow></mfrac>");
        } else if (rightTermsTop.length > 0) {
          rightSide.push(rightTermsTop.join("<mo>&middot;</mo>"));
        } else if (rightTermsBottom.length > 0) {
          rightSide.push("<mfrac><mrow><mn>1</mn></mrow><mrow>" + rightTermsBottom.join("<mo>&middot;</mo>") + "</mrow></mfrac>");
        }
        html += rightSide.join("<mo>&middot;</mo>") + "</math>";
        return html;
      };

      return Equation;

    })();
  });

}).call(this);
