// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var makeEquation, makeExpression;
    makeEquation = function(mathML) {
      var element;
      element = $("<math>" + mathML + "</math>");
      element.attr("id", "equation");
      return element;
    };
    makeExpression = function(mathML) {
      var element;
      element = $("<math>" + mathML + "</math>");
      element.attr("id", "expression");
      return element;
    };
    return {
      makeEquation: makeEquation,
      makeExpression: makeExpression
    };
  });

}).call(this);
