// Generated by CoffeeScript 1.6.3
/*
Graphical Equation Manipulator

Matthew Alger, based on Buck Shlegeris' pyGEM.
https://github.com/MatthewJA/Graphical-Equation-Manipulator
https://github.com/bshlgrs/pyGEM

Licensed under GPL v3.
*/


(function() {
  require.config({
    baseUrl: "./src",
    paths: {
      jquery: "vendor/jquery-2.1.1.min"
    }
  });

  require(["jquery"], function($) {
    return window.gem.loaded = true;
  });

}).call(this);
