// Generated by CoffeeScript 1.6.3
(function() {
  var bodies, closePreloader, closingPreloader, dt, height, lastUpdate, opacity, preloader, sim, width;

  window.gem = {};

  preloader = document.getElementById("preloader");

  bodies = {
    sun: {
      position: [0, 0],
      speed: 0,
      element: document.getElementById("preloader-sun")
    },
    venus: {
      position: [80, 0],
      speed: 40 * Math.PI / 40000,
      element: document.getElementById("preloader-venus")
    },
    earth: {
      position: [120, 0],
      speed: 24 * Math.PI / 40000,
      element: document.getElementById("preloader-earth")
    },
    mars: {
      position: [160, 0],
      speed: 12 * Math.PI / 40000,
      element: document.getElementById("preloader-mars")
    },
    jupiter: {
      position: [220, 0],
      speed: 2 * Math.PI / 40000,
      element: document.getElementById("preloader-jupiter")
    }
  };

  width = preloader.clientWidth;

  height = preloader.clientHeight;

  lastUpdate = (new Date()).getTime() - Math.random() * 20000;

  dt = 0;

  opacity = 1.0;

  closingPreloader = true;

  sim = function() {
    var body, now, x, y;
    now = (new Date()).getTime();
    dt = now - lastUpdate;
    lastUpdate = now;
    for (body in bodies) {
      x = width / 2 - bodies[body].element.clientWidth / 2 + bodies[body].position[0] * Math.cos(bodies[body].position[1]);
      y = height / 2 - bodies[body].element.clientHeight / 2 + bodies[body].position[0] * Math.sin(bodies[body].position[1]);
      bodies[body].element.style.left = "" + x + "px";
      bodies[body].element.style.top = "" + y + "px";
      bodies[body].position[1] = (bodies[body].position[1] + bodies[body].speed * dt) % (Math.PI * 2);
    }
    if (window.gem.loaded == null) {
      return setTimeout(sim, 0);
    } else {
      return setTimeout(closePreloader, 0);
    }
  };

  closePreloader = function() {
    if (closingPreloader) {
      opacity -= 0.02;
      document.getElementById("loader").style.opacity = "" + opacity;
      if (opacity <= 0) {
        closingPreloader = false;
        document.getElementById("loader").style.display = "none";
        return setTimeout(closePreloader, 0);
      } else {
        return setTimeout(sim, 0);
      }
    } else {
      opacity += 0.02;
      document.getElementById("whiteboard").style.display = "block";
      document.getElementById("whiteboard").style.opacity = "" + opacity;
      if (opacity < 1) {
        return setTimeout(closePreloader, 0);
      } else {
        return window.gem.preloaderClosed = true;
      }
    }
  };

  sim();

}).call(this);
