// Generated by CoffeeScript 1.6.3
(function() {
  define(["mathjax"], function(MathJax) {
    var math;
    math = function() {
      return MathJax.Hub.Queue([MathJax.Hub, "Typeset", "#whiteboard"]);
    };
    return {
      math: math
    };
  });

}).call(this);
