// Generated by CoffeeScript 1.6.3
(function() {
  define(["JSAlgebra/constant"], function(Constant) {
    return describe("Constants", function() {
      it("can be simplified", function() {
        var half;
        half = new Constant(2, 4);
        half.simplify();
        return expect(half).toEqual(new Constant(1, 2));
      });
      return it("can be made into non-decimal forms", function() {
        var half;
        half = new Constant(0.5);
        half.simplify();
        return expect(half).toEqual(new Constant(1, 2));
      });
    });
  });

}).call(this);
