// Generated by CoffeeScript 1.6.3
(function() {
  define(["JSAlgebra/variable", "JSAlgebra/constant", "JSAlgebra/equation", "JSAlgebra/algebraException"], function(Variable, Constant, Equation, AlgebraException) {
    return describe("Fails reasonably when", function() {
      it("attempting to solve an equation for a variable it does not contain", function() {
        var equation;
        equation = new Equation(["a"], ["b"]);
        return expect(function() {
          return equation.solve("z");
        }).toThrow(new AlgebraException("Variable to solve for was not in equation."));
      });
      return it("attempting to substitute values that make no sense", function() {
        var equation;
        equation = new Equation(["a"], ["b"]);
        return expect(function() {
          return equation.sub({
            "a": 1,
            "b": 2
          });
        }).toThrow(new AlgebraException("Inconsistent numbers substituted into equation."));
      });
    });
  });

}).call(this);
