// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: "../src",
    urlArgs: "cb=" + Math.random(),
    paths: {
      "spec": "../tests/spec",
      "jquery": "../tests/jquery.min",
      "JSAlgebra": "../src"
    },
    shim: {
      "jquery": {
        exports: ["jquery"]
      }
    }
  });

  require(["jquery"], function($) {
    var htmlReporter, jasmineEnv, specs;
    jasmineEnv = jasmine.getEnv();
    htmlReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(htmlReporter);
    specs = ["spec/failure", "spec/simpleEquations", "spec/evaluation", "spec/constants"];
    jasmineEnv.specFilter = function(spec) {
      return htmlReporter.specFilter(spec);
    };
    return $(function() {
      return require(specs, function() {
        return jasmineEnv.execute();
      });
    });
  });

}).call(this);
